### ISSUE TITLE
getting this issue when running main.py

### ISSUE THREAD

**Issue by BadBadBoss** [kWAYTV/telegram-adbot#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\telegram-adbot-main\telegram-adbot-main\main.py", line 35, in <module>
    Tool = Main()
  File "C:\Users\Administrator\Desktop\telegram-adbot-main\telegram-adbot-main\main.py", line 20, in __init__
    self.shiller = Shiller()
  File "C:\Users\Administrator\Desktop\telegram-adbot-main\telegram-adbot-main\src\modules\telegram\telegram.py", line 17, in __init__
    self.client = TelegramClient('src/data/sessions/anon', self.config.api_id, self.config.api_hash, sequential_updates=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\telegrambaseclient.py", line 289, in __init__
    session = SQLiteSession(session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sessions\sqlite.py", line 47, in __init__
    c = self._cursor()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\sessions\sqlite.py", line 242, in _cursor
    self._conn = sqlite3.connect(self.filename,
sqlite3.OperationalError: unable to open database file

**Comment by kWAYTV** [comment]
Did you fill the config file properly?

**Comment by BadBadBoss** [comment]
yes I can dm you it if you want?

**Comment by kWAYTV** [comment]
@kwaytv in telegram
